### ISSUE TITLE
Deploying on Ubuntu 20.10

### ISSUE THREAD

**Issue by official-antique** [popcorn-time-ru/popcorn-ru#10]
Just wondering what is needed to deploy this on Ubuntu, currently only for local testing.

I've gotten to the database creation but it doesn't contain an 'enqueue' table and running 'bin/console spider:run --all' doesn't do anything I believe.

**Comment by ivan1986** [comment]
Forgot `bin/console enqueue:setup-broker`, sorry, fixed.
run `bin/console enqueue:setup-broker` after create schema

**Comment by official-antique** [comment]
I'll give that a shot tomorrow, thank you!

**Comment by official-antique** [comment]
Running pgrep... only grabs 2-40 items, is there something else I'm missing?
> I'm new to PHP stuff but have gotten a majority of this to work.

@ivan1986

**Comment by ivan1986** [comment]
for wich time? It's ok - many limits, look in enqueue table - should be many tasks

**Comment by official-antique** [comment]
I'm now running into this issue, is there a way to skip over failed getMedia queries? My database is about 90MB in size now.

![image](https://user-images.githubusercontent.com/69136905/115100822-dcd50180-9f71-11eb-88f8-e5e95790284d.jpeg)

**Comment by ivan1986** [comment]
hm, do you clean torrrnt table?
it's imposible case
ok, add check

**Comment by official-antique** [comment]
I believe I'm doing something wrong, I've been running it for days and only have 250MB and about 120 pages of movies.

**Comment by hotsjf** [comment]
I think the movie loads pretty slow. it takes weeks. 
as long as it's adding new movies, give it some time.

**Comment by ivan1986** [comment]
@official-antique 
do you run `bin/conole spider:run --all` ?
because in cron only new films for last 48 hours

**Comment by official-antique** [comment]
I've not run that every couple days, I'm running the enqueue with no time or memory limit to make it run forever.

I saw your API has 1000's of pages but mine seems to have 120 or so.

**Comment by ivan1986** [comment]
in addition to the queue, you need to run a start script that starts scanning anew the initial pages of the forums, by default it is configured to start every day with checking for topics newer than 48 hours.
For the first launch, you need to run without the --last parameter

You can see what you have in the parsing queue right now
```
select count(*)                                        c,
       json_extract(properties, '$.\"enqueue.topic\"') topic,
       json_extract(body, '$.spider')                  spider,
       json_extract(body, '$.type')                    type
from enqueue
group by topic, spider, type;
```
Sorry, but now admin and statustic pages not ready
