### ISSUE TITLE
Issue sorting by note

### ISSUE THREAD

**Issue by MecMada** [popcorn-time-ru/popcorn-ru#14]
Operating System Version:
Windows10

Popcorn Time Version:
0.4.4

Download date:
16/05/2021

Download url (optional):
http://popcorn-ru.tk/build/Popcorn-Time-0.4.4-win64-Setup.exe

Expected Behaviour
When sorted by note, the first film should have the best note.

Actual Behaviour
When sorted by note, I have "The fast and Furious Tokyo Drift" in choice 1 (6.3/10 IMDb note) and "Blood diamond" in choice 2 (7.5/10 IMDb score)

Steps to reproduce the behaviour
Sort by note

Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab)
![image](https://user-images.githubusercontent.com/66328163/118394326-4b29e400-b644-11eb-92c9-325cf3d0db2d.png)

**Comment by ivan1986** [comment]
Ok, it's incorrect, but same as old api sort

for now get max count votes, but get max rating also incorret

For now i just add this
https://www.evanmiller.org/how-not-to-sort-by-average-rating.html
https://www.evanmiller.org/bayesian-average-ratings.html
https://fulmicoton.com/posts/bayesian_rating/

**Comment by ivan1986** [comment]
https://github.com/popcorn-official/popcorn-api/blob/development/src/controllers/ContentController.js#L69

**Comment by ivan1986** [comment]
switch ro rating and popularity

**Comment by ivan1986** [comment]
now cache cleaned and sort by rating
but it's garbage, because on top films and series with 10-20 votes
for now calculating weight rating, after it will be ready - switch.

**Comment by ivan1986** [comment]
all sorting fixed
