### ISSUE TITLE
Initialisation Error

### ISSUE THREAD

**Issue by allamelia** [popcorn-time-ru/popcorn-ru#15]
Upon installation and first run, following the instructions and running:
> bin/console spider:run --all

The following error message is shown and the script halts:

>In EnvVarProcessor.php line 172:
>
>Environment variable not found: "ELASTICSEARCH_URL".
>
>
>2021-07-12T21:09:45+00:00 [info] User Deprecated: Since symfony/property-access 5.3: Passing a boolean as the second argument to "Symfony\Component\PropertyAccess\PropertyAccessor::__construct()" is deprecated. Pass a combination of bitwise flags instead (i.e an integer).
>root@popcorn:/var/www/html#

Checking in the MySQL database confirms that no data was scraped.

**Comment by ivan1986** [comment]
`ELASTICSEARCH_URL` exist in `.env` looks like you change something

**Comment by allamelia** [comment]
I've updated the .env file with the variable in .env within this branch. Now when running I get the following below, does the script not start elastic search?

> pgrep -c -f enqueue:consume || bin/console enqueue:consume --time-limit="now + 55 minutes" --no-debug --memory-limit=200


> [app] Couldn't connect to host, Elasticsearch down? ["trace"                                                                                                                                                                              => """  #0 /var/www/html/vendor/ruflin/elastica/src/Request.php(181): Elastica\T                                                                                                                                                                             ransport\Http->exec()\n  #1 /var/www/html/vendor/ruflin/elastica/src/Client.php(                                                                                                                                                                             512): Elastica\Request->send()\n  #2 /var/www/html/vendor/friendsofsymfony/elast                                                                                                                                                                             ica-bundle/src/Elastica/Client.php(60): Elastica\Client->request()\n  #3 /var/ww                                                                                                                                                                             w/html/vendor/ruflin/elastica/src/Bulk.php(290): FOS\ElasticaBundle\Elastica\Cli                                                                                                                                                                             ent->request()\n  #4 /var/www/html/vendor/ruflin/elastica/src/Client.php(218): E                                                                                                                                                                             lastica\Bulk->send()\n  #5 /var/www/html/vendor/ruflin/elastica/src/Index.php(16                                                                                                                                                                             0): Elastica\Client->updateDocuments()\n  #6 /var/www/html/vendor/friendsofsymfo                                                                                                                                                                             ny/elastica-bundle/src/Persister/ObjectPersister.php(118): Elastica\Index->updat                                                                                                                                                                             eDocuments()\n  #7 /var/www/html/vendor/friendsofsymfony/elastica-bundle/src/Doc                                                                                                                                                                             trine/Listener.php(199): FOS\ElasticaBundle\Persister\ObjectPersister->replaceMa                                                                                                                                                                             ny()\n  #8 /var/www/html/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/Li                                                                                                                                                                             stener.php(174): FOS\ElasticaBundle\Doctrine\Listener->persistScheduled()\n  #9                                                                                                                                                                              /var/www/html/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php(68):                                                                                                                                                                              FOS\ElasticaBundle\Doctrine\Listener->postFlush()\n  #10 /var/www/html/vendor/d                                                                                                                                                                             octrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3457): Symfony\Bridge\Doctrine\Conta                                                                                                                                                                             inerAwareEventManager->dispatchEvent()\n  #11 /var/www/html/vendor/doctrine/orm/                                                                                                                                                                             lib/Doctrine/ORM/UnitOfWork.php(475): Doctrine\ORM\UnitOfWork->dispatchPostFlush                                                                                                                                                                             Event()\n  #12 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.                                                                                                                                                                             php(378): Doctrine\ORM\UnitOfWork->commit()\n  #13 /var/www/html/var/cache/dev/C                                                                                                                                                                             ontainerZbKnY6y/App_KernelDevContainer.php(7151): Doctrine\ORM\EntityManager->fl                                                                                                                                                                             ush()\n  #14 /var/www/html/src/Service/TorrentService.php(137): ContainerZbKnY6y                                                                                                                                                                             \EntityManager_9a5be93->flush()\n  #15 /var/www/html/src/Spider/Eztv.php(122): A                                                                                                                                                                             pp\Service\TorrentService->updateTorrent()\n  #16 /var/www/html/src/Spider/Eztv.                                                                                                                                                                             php(58): App\Spider\Eztv->buildFromTorrentData()\n  #17 /var/www/html/src/Proces                                                                                                                                                                             sors/ForumProcessor.php(53): App\Spider\Eztv->getPage()\n  #18 /var/www/html/ven                                                                                                                                                                             dor/enqueue/enqueue/Client/DelegateProcessor.php(38): App\Processors\ForumProces                                                                                                                                                                             sor->process()\n  #19 /var/www/html/vendor/enqueue/enqueue/Consumption/QueueCons                                                                                                                                                                             umer.php(197): Enqueue\Client\DelegateProcessor->process()\n  #20 [internal func                                                                                                                                                                             tion]: Enqueue\Consumption\QueueConsumer->Enqueue\Consumption\{closure}()\n  #21                                                                                                                                                                              /var/www/html/vendor/enqueue/dbal/DbalSubscriptionConsumer.php(113): call_user_                                                                                                                                                                             func()\n  #22 /var/www/html/vendor/enqueue/enqueue/Consumption/QueueConsumer.php                                                                                                                                                                             (264): Enqueue\Dbal\DbalSubscriptionConsumer->consume()\n  #23 /var/www/html/ven                                                                                                                                                                             dor/enqueue/enqueue/Symfony/Client/ConsumeCommand.php(144): Enqueue\Consumption\                                                                                                                                                                             QueueConsumer->consume()\n  #24 /var/www/html/vendor/symfony/console/Command/Com                                                                                                                                                                             mand.php(299): Enqueue\Symfony\Client\ConsumeCommand->execute()\n  #25 /var/www/                                                                                                                                                                             html/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Comm                                                                                                                                                                             and\Command->run()\n  #26 /var/www/html/vendor/symfony/framework-bundle/Console/                                                                                                                                                                             Application.php(96): Symfony\Component\Console\Application->doRunCommand()\n  #2                                                                                                                                                                             7 /var/www/html/vendor/symfony/console/Application.php(295): Symfony\Bundle\Fram                                                                                                                                                                             eworkBundle\Console\Application->doRunCommand()\n  #28 /var/www/html/vendor/symf                                                                                                                                                                             ony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Appl                                                                                                                                                                             ication->doRun()\n  #29 /var/www/html/vendor/symfony/console/Application.php(167                                                                                                                                                                             ): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()\n  #30 /var/www/h                                                                                                                                                                             tml/bin/console(42): Symfony\Component\Console\Application->run()\n  #31 {main}                                                                                                                                                                               ""","extra" => ["trace" => """  #0 /var/www/html/vendor/ruflin/elastica/src/Req                                                                                                                                                                             uest.php(181): Elastica\Transport\Http->exec()\n  #1 /var/www/html/vendor/ruflin                                                                                                                                                                             /elastica/src/Client.php(512): Elastica\Request->send()\n  #2 /var/www/html/vend                                                                                                                                                                             or/friendsofsymfony/elastica-bundle/src/Elastica/Client.php(60): Elastica\Client                                                                                                                                                                             ->request()\n  #3 /var/www/html/vendor/ruflin/elastica/src/Bulk.php(290): FOS\El                                                                                                                                                                             asticaBundle\Elastica\Client->request()\n  #4 /var/www/html/vendor/ruflin/elasti                                                                                                                                                                             ca/src/Client.php(218): Elastica\Bulk->send()\n  #5 /var/www/html/vendor/ruflin/                                                                                                                                                                             elastica/src/Index.php(160): Elastica\Client->updateDocuments()\n  #6 /var/www/h                                                                                                                                                                             tml/vendor/friendsofsymfony/elastica-bundle/src/Persister/ObjectPersister.php(11                                                                                                                                                                             8): Elastica\Index->updateDocuments()\n  #7 /var/www/html/vendor/friendsofsymfon                                                                                                                                                                             y/elastica-bundle/src/Doctrine/Listener.php(199): FOS\ElasticaBundle\Persister\O                                                                                                                                                                             bjectPersister->replaceMany()\n  #8 /var/www/html/vendor/friendsofsymfony/elasti                                                                                                                                                                             ca-bundle/src/Doctrine/Listener.php(174): FOS\ElasticaBundle\Doctrine\Listener->                                                                                                                                                                             persistScheduled()\n  #9 /var/www/html/vendor/symfony/doctrine-bridge/ContainerA                                                                                                                                                                             wareEventManager.php(68): FOS\ElasticaBundle\Doctrine\Listener->postFlush()\n  #                                                                                                                                                                             10 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3457): Symf                                                                                                                                                                             ony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent()\n  #11 /var/www/                                                                                                                                                                             html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(475): Doctrine\ORM\Unit                                                                                                                                                                             OfWork->dispatchPostFlushEvent()\n  #12 /var/www/html/vendor/doctrine/orm/lib/Do                                                                                                                                                                             ctrine/ORM/EntityManager.php(378): Doctrine\ORM\UnitOfWork->commit()\n  #13 /var                                                                                                                                                                             /www/html/var/cache/dev/ContainerZbKnY6y/App_KernelDevContainer.php(7151): Doctr                                                                                                                                                                             ine\ORM\EntityManager->flush()\n  #14 /var/www/html/src/Service/TorrentService.p                                                                                                                                                                             hp(137): ContainerZbKnY6y\EntityManager_9a5be93->flush()\n  #15 /var/www/html/sr                                                                                                                                                                             c/Spider/Eztv.php(122): App\Service\TorrentService->updateTorrent()\n  #16 /var/                                                                                                                                                                             www/html/src/Spider/Eztv.php(58): App\Spider\Eztv->buildFromTorrentData()\n  #17                                                                                                                                                                              /var/www/html/src/Processors/ForumProcessor.php(53): App\Spider\Eztv->getPage()                                                                                                                                                                             \n  #18 /var/www/html/vendor/enqueue/enqueue/Client/DelegateProcessor.php(38): A                                                                                                                                                                             pp\Processors\ForumProcessor->process()\n  #19 /var/www/html/vendor/enqueue/enqu                                                                                                                                                                             eue/Consumption/QueueConsumer.php(197): Enqueue\Client\DelegateProcessor->proces                                                                                                                                                                             s()\n  #20 [internal function]: Enqueue\Consumption\QueueConsumer->Enqueue\Consu                                                                                                                                                                             mption\{closure}()\n  #21 /var/www/html/vendor/enqueue/dbal/DbalSubscriptionCons                                                                                                                                                                             umer.php(113): call_user_func()\n  #22 /var/www/html/vendor/enqueue/enqueue/Cons                                                                                                                                                                             umption/QueueConsumer.php(264): Enqueue\Dbal\DbalSubscriptionConsumer->consume()                                                                                                                                                                             \n  #23 /var/www/html/vendor/enqueue/enqueue/Symfony/Client/ConsumeCommand.php(1                                                                                                                                                                             44): Enqueue\Consumption\QueueConsumer->consume()\n  #24 /var/www/html/vendor/sy                                                                                                                                                                             mfony/console/Command/Command.php(299): Enqueue\Symfony\Client\ConsumeCommand->e                                                                                                                                                                             xecute()\n  #25 /var/www/html/vendor/symfony/console/Application.php(996): Symfo                                                                                                                                                                             ny\Component\Console\Command\Command->run()\n  #26 /var/www/html/vendor/symfony/                                                                                                                                                                             framework-bundle/Console/Application.php(96): Symfony\Component\Console\Applicat                                                                                                                                                                             ion->doRunCommand()\n  #27 /var/www/html/vendor/symfony/console/Application.php(                                                                                                                                                                             295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()\n  #28                                                                                                                                                                              /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfo                                                                                                                                                                             ny\Component\Console\Application->doRun()\n  #29 /var/www/html/vendor/symfony/co                                                                                                                                                                             nsole/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->                                                                                                                                                                             doRun()\n  #30 /var/www/html/bin/console(42): Symfony\Component\Console\Applicat                                                                                                                                                                             ion->run()\n  #31 {main}  """]]

**Comment by ivan1986** [comment]
> Couldn't connect to host, Elasticsearch down

no, not start - setup and start
