### ISSUE TITLE
403 Forbidden reponse

### ISSUE THREAD

**Issue by Aransh** [popcorn-time-ru/popcorn-ru#19]
Getting 403 forbidden from cloudflare when trying to access the API from PopcornTime on my Apple TV.
Been this way for a few weeks now, worked fine before... (still works fine from my Mac) any clue? any header I need to add to the request maybe?

**Comment by ivan1986** [comment]
PopcornTime on Apple TV?
Not exist PopcornTime for Apple TV
We ban some ip's with many scan requests
Understand what kind of garbage you downloaded and complain to the developers of your client, who cannot normally ask, but instead write spam proxies

**Comment by NSExceptional** [comment]
@ivan1986 This is the issue I was having, so I'll leave my issue closed. I mistakenly said 408 in my title I think.

I have taken over maintenance of the PopcornTime Apple TV app. Looks like you're blocking us based on our header:
```
Popcorn%20Time/1 CFNetwork/1209 Darwin/19.5.0
```

I get `403` with this header and `200` without it.

**Comment by ivan1986** [comment]
We have many custom mac/ios clients, and no one unknown in forum
Also we have many other apps, which ask money by patreon
If you maintain ios version give link to packages or to install guide, or give packages and we put it on build dir
for now turn off blocking

**Comment by NSExceptional** [comment]
My fork is [here](https://github.com/NSExceptional/PopcornTimeTV). Its not in great shape yet but it's working.

If you have access to the original repository, add me as a contributor and I can unarchive the repo and merge my changes

**Comment by ivan1986** [comment]
ok, i haven't access to ios repo ( https://github.com/popcorn-official/PopcornTimeTV/ ), and it's broken
i ask team, and somebody should has access

**Comment by ivan1986** [comment]
PopcornTimeTV/PopcornTimeTV is archived and nobody has access
and sorry i havn't access to any of https://github.com/popcorn-official/
i write to team, but not get response yet

**Comment by NSExceptional** [comment]
Okay, gotcha. Keep me updated if you can, thanks!
