### ISSUE TITLE
How to add this to Popcorn Time a plugin for KODI?

### ISSUE THREAD

**Issue by pizdjuk** [popcorn-time-ru/popcorn-ru#2]
I didnt find the similarities between this trees....

**Comment by ivan1986** [comment]
it's server, not client
you need change api in plugin
send locale and get translated titles form new part of api
api is same as original

**Comment by lubo** [comment]
Done in markop159/KODI-Popcorn-Time@03d292905e30b356f64dbc724a8727ae62af154f, I believe this can be closed.

**Comment by ivan1986** [comment]
@lubo Oh, i see you last commit - you switch to ga, cool
but will be very good if you implement load configs for dht, how it's made in 0.4.7 decktop
