### ISSUE TITLE
Around the World in 80 days

### ISSUE THREAD

**Issue by keswickian123** [popcorn-time-ru/popcorn-ru#25]
8 episodes listed. 1 and 2 are fine but 3 to 8 are all episode 2.

?????????

**Comment by ivan1986** [comment]
hm
for me all works correct
1 and 2 exist in 1080
and all s1 in 720 and correct link to series

**Comment by keswickian123** [comment]
Then perhaps you can explain this?
[Around the World.pdf](https://github.com/popcorn-time-ru/popcorn-ru/files/7834768/Around.the.World.pdf)

**Comment by ivan1986** [comment]
![image](https://user-images.githubusercontent.com/156418/148676935-e1ed3c18-e100-441c-bebc-75abf00ef927.png)
![image](https://user-images.githubusercontent.com/156418/148676997-0dfd814d-a7eb-4d06-a851-30be462bafef.png)

what client version you use? in old verions may be bug in file selection

**Comment by keswickian123** [comment]
Not sure. What is the latest version? Let me try that.

**Comment by keswickian123** [comment]
0.4.5 I think

**Comment by ivan1986** [comment]
yep, it's fix in 0.4.6 - file path in windows (windows and unix slash in path compare)
try latest release http://popcorn-ru.tk/build/
or better http://popcorn-ru.tk/build/dev/ - it's allmost 0.4.7 with auto server configure

**Comment by keswickian123** [comment]
Thank you Ivan 

I really appreciate your help.

**Comment by ivan1986** [comment]
fixed
