### ISSUE TITLE
Selecting 2160p but the file is 1080p sometimes

### ISSUE THREAD

**Issue by baptisteArno** [popcorn-time-ru/popcorn-ru#26]
Sometimes I'm asking for 2160p but it downloads 1080p videos.

How does this work exactly? Can I improve this in any way?

To reproduce:
Search for Ted Lasso S02E05 for example. The file comes from `https://torrentgalaxy.to/` and when manually searching in torrentgalaxy I can find a 2160p file

**Comment by ivan1986** [comment]
Parser get quality from torrent page, in this case it found 2160 in description and set to 2160p
you may try to make parser better

**Comment by baptisteArno** [comment]
I'm thinking maybe parsing the quality from title instead of description? And eventually parsing the description if the title doesn't contain quality?

**Comment by ivan1986** [comment]
yes, it's good solution, and need refactor this part

**Comment by ivan1986** [comment]
added priority to title

**Comment by baptisteArno** [comment]
Awesome, thank you @ivan1986 💪

**Comment by baptisteArno** [comment]
When will it be taken into account?
If I understood correctly the cron file, the scrapper is ran every month only? What am I missing?

**Comment by ivan1986** [comment]
recheck exist torrents one time in 6 month
set active maual for this
will be today, after caches flush

**Comment by ivan1986** [comment]
ok, fixed
