### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by Suor** [popcorn-time-ru/popcorn-ru#3]
I installed 0.4.4 deb from releases but I don't see anything from rutracker there. Some README would help a lot.

**Comment by ivan1986** [comment]
Waht you see? Films and shows on russian? Source not show now, what need in readme for server part exept url to api?

**Comment by Suor** [comment]
First thing it should say that it is server part. Then how to install and run it. Or should I?

Currently I don't see anything in russian there.

**Comment by Suor** [comment]
I simply came from [here](http://popcorn-ru.tk/), installed deb from releases link from there. This is also confusing that link to releases on github and link "Fork on github" leads to different repos.

**Comment by ivan1986** [comment]
You not need install this - it's a server, and you not need do anything with this for use popcorn time - just download client - server url exist in config/ you need use this only if you want you own server fox example with russian film, or add some trackers/

**Comment by Suor** [comment]
So it's already set up somewhere? Where do I found that `config/` dir? Do I need to copy url form there to UI?

**Comment by Suor** [comment]
Basically [this page](http://popcorn-ru.tk/) that this will work with Rutracker and other things, but it doesn't. There is no README that says how to set it up.

**Comment by ivan1986** [comment]
It's already setup in `/opt/Popcorn-Time-Ru/node_modules/butter-settings-popcorntime.ru/index.js`

Why you think it not work with rutracker? Just run `curl "http://popcorn-ru.tk/movies/1?locale=ru" | jq . | grep rutracker `

**Comment by Suor** [comment]
Here is an example. There are way more things on rutracker.

![popcorn-ru](https://user-images.githubusercontent.com/284103/81297385-5e9f8800-909d-11ea-81e4-f91635e025dc.png)

**Comment by ivan1986** [comment]
set lanuage in settings to russian. you have english locale by default?

**Comment by Suor** [comment]
Set to russian, looks the same:

![popcorn-ru-ru](https://user-images.githubusercontent.com/284103/81300660-22225b00-90a2-11ea-9d23-307f0f39da94.png)

Yes, I have english by default.

**Comment by ivan1986** [comment]
![1](https://user-images.githubusercontent.com/156418/81300996-25591f00-9081-11ea-9d0b-651e3d8575ce.png)
for me this, do you restart app after change lang?

**Comment by Suor** [comment]
Ok, after the restart it looks the same as yours, but rutracker has far more stuff.

**Comment by ivan1986** [comment]
For hell kitchen - i don't know why reality show it in learning video.
I look only films and shows, and drop russian, indian and other shit.
https://github.com/popcorn-time-ru/popcorn-ru/blob/master/src/Spider/Rutracker.php#L47

**Comment by qarkai** [comment]
> drop russian

Then it's useless for some family members, e.g. grandparents watch mostly Russian or even Soviet movies. Could you add an option to include Russian movies and shows in search?

**Comment by ivan1986** [comment]
@qarkai No, i can not add option for this - need to add custom filter, you are first who ask about this. If you want you may get code, deploy it to VDS (free tier google is greate for this) and configure parsers for any shit like soviet movies or bollywood.
PS: Также у меня совершенно нет желания делать что-то хорошее для любителей совка и патриотов россии, делайте сами, посмотрите сколько к вам будут ходить на сервер.

**Comment by qarkai** [comment]
@ivan1986 Yes, you can. Adding custom filter is the main point of request.

**Comment by ivan1986** [comment]
@qarkai Of course, I can do a bunch of crutches, mark these films in some way by rewriting the parsers, and show them depending on the flag, but as I already wrote I don't want to waste my time on this.
Set up your server and collect any kunskamera there, especially since I myself added filters to exclude soviet and russian films.
