### ISSUE TITLE
It takes too much time for new episodes to become available

### ISSUE THREAD

**Issue by lubo** [popcorn-time-ru/popcorn-ru#31]
Currently, Family Guy S20E12 (available on TPB since February 28) and South Park S25E04 (available on TPB since March 3) are still not available. There's been a trend over the past several months of new episodes taking longer and longer to become available via the API.

**Comment by ivan1986** [comment]
We not parse TPB :(
Ok, need write new spiders, and looks like current server can't parse all and handle all requests
Sorry, not much time for this project now
