### ISSUE TITLE
Subtitles are stuck in one position.

### ISSUE THREAD

**Issue by CortexReaver** [popcorn-time-ru/popcorn-ru#41]
Sometimes subtitles are stuck in one position, and to fix it you need to cancel watching and then start it again. After 2 or more restarts it might help and they work again as intended.

**Comment by ivan1986** [comment]
It's not server issue
https://github.com/popcorn-official/popcorn-desktop/issues

**Comment by CortexReaver** [comment]
ah, sorry. Might've been clicked the wrong link and confused two separate projects as a result. I will create issue there, thank you.
