### ISSUE TITLE
[nested] failed to find nested object under path [rating] [index: movies] [reason: all shards failed]

### ISSUE THREAD

**Issue by ottar-eten-yod** [popcorn-time-ru/popcorn-ru#53]
Possibly related to https://github.com/popcorn-time-ru/popcorn-ru/commit/242bdb06ff992b98422686235a642565d2e8c404

**Comment by ivan1986** [comment]
i fix it after error in prod
elastic 8.4.2, create index and populate after move

**Comment by ottar-eten-yod** [comment]
Hmm odd. I clone the repository like fresh. Then I remove that commits changes and the error is gone. But then none of the data is showing up on the API page so.

**Comment by ivan1986** [comment]
fixed

**Comment by 8KV** [comment]
> fixed

I just did a fresh install but the problem still persists.

**Comment by ivan1986** [comment]
it was fixed long time ago and work on prod
check local elastic version and check indexes

**Comment by 8KV** [comment]
> it was fixed long time ago and work on prod check local elastic version and check indexes

I used the guide from the documentation. Is the version outdated there?

**Comment by ivan1986** [comment]
no, it's last version

**Comment by 8KV** [comment]
> it was fixed long time ago and work on prod check local elastic version and check indexes

How do I check the indexes?

**Comment by ivan1986** [comment]
http://localhost:9200/_aliases
http://localhost:9200/_cluster/health
run fos:elastica:populate

**Comment by 8KV** [comment]
> fos:elastica:populate

Fixed it. Thank You very much.
