### ISSUE TITLE
Any options to filter only films with enabled russian audiotrack

### ISSUE THREAD

**Issue by alexkutsan** [popcorn-time-ru/popcorn-ru#6]
I don't know why but in Popcorntime on android most of the films contains russian language. But in Linux not. In Linux there mostely only one audio track - english. 
Is there different source on android and Linux? 
And may I put some kind of filter for desired audiotrac?

**Comment by ivan1986** [comment]
Do you use ru fork, and do you select russian interface? Ru fork client send current language to server, and english is default for back compatible. Source is same, but for non english content need fork client
