### ISSUE TITLE
popcorn-time.ga is down?

### ISSUE THREAD

**Issue by sweetw0r** [popcorn-time-ru/popcorn-ru#63]
Getting redirected

```
{
  "repo": "https://github.com/popcorn-time-ru/popcorn-ru",
  "server": "serv01",
  "status": "idle",
  "totalAnimes": 0,
  "totalMovies": 70000,
  "totalShows": 9000,
  "updated": 1686887419,
  "uptime": 100000,
  "version": "0.0.1",
  "commit": "ac462477"
}
```

**Comment by dlevi309** [comment]
I checked a couple of days ago and checked again now, I think someone may have swiped the domain name /:

**Comment by dlevi309** [comment]
@ivan1986 Hey Ivan, I saw that you closed this issue, so I’ll keep it short and brief: just want to know, is the public api server for this project gone for good? or is there any other IP address/domain to direct my own client to. 

regardless, thank you for keeping this project alive!
best regards

**Comment by ivan1986** [comment]
read on reddit, it's default situation, we lost main domain many time, application get endpoints from dht
endpoint in first on comment it's `/status` - only plug for kodi plugin
for you own client need implement update config - for example android:

https://github.com/popcorn-official/popcorn-android/commit/560d52e2ab94bd6679f9fdba028718015e9d470f
https://github.com/popcorn-official/popcorn-android/commit/877ab95af5e55e5e4a25a3f15613da763ebd88ba
https://github.com/popcorn-official/popcorn-android/commit/905a0142d1ce7ffd85eb2b118339756fc1226842

default client - https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/dht.js#L23
just update periodic and use server value from info
