### ISSUE TITLE
Detailed Google Cloud instructions

### ISSUE THREAD

**Issue by swingchampion** [popcorn-time-ru/popcorn-ru#8]
I would like to set up the API Server on a paid Google Cloud tier. Unfortunately, I don't know exactly where to start because I'm not very familiar with server hosting. Could you maybe create a detailed guide? If you want, I could also set up a paid tier for you.

**Comment by ivan1986** [comment]
Be carefull with google - i get bill for outgoing trafic after end free tier, and now switch to oracle cloud - free tier in oracle is owerkill for me :)
Oh, I can't write good manuals :)

For this you need only one vm and on paid you can use cloud sql, and i think small vm is math more what need for this project - it's only db (285 mb now), tor proxy, cron script and php-fpm + nginx cache
i not try to up it in google app engine, i use computer engine and configure it as simple vm and it's classic php web application.

Hmm, maybe i help you setup server? For me is real hard to write guide :)

**Comment by swingchampion** [comment]
Thank you for pointing this out. I would be very happy if you could help me? Do you have Discord or something else so we could communicate more easily?

**Comment by ivan1986** [comment]
yes, discord **Ivan1986**, but sorry if i will stuped first time - i use it only one time :)

**Comment by swingchampion** [comment]
No problem. I would also need your # to add you.

**Comment by ivan1986** [comment]
Ivan1986#7040
